services:
  database:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_DB},pinkka_test_db
    ports:
      - "5432:5432"
    volumes:
      - pinkka_db:/var/lib/postgresql
      - ./scripts/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: pinkka-backend
    env_file:
      - apps/backend/.env
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  pinkka_db:
