/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/app/home'
import { Route as AuthenticatedAppCategoriesRouteRouteImport } from './routes/_authenticated/app/categories/route'
import { Route as AuthenticatedAppAdminRouteRouteImport } from './routes/_authenticated/app/admin/route'
import { Route as AuthenticatedAppAccountsRouteRouteImport } from './routes/_authenticated/app/accounts/route'
import { Route as AuthenticatedAppCategoriesIndexRouteImport } from './routes/_authenticated/app/categories/index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app/admin/index'
import { Route as AuthenticatedAppAccountsIndexRouteImport } from './routes/_authenticated/app/accounts/index'
import { Route as AuthenticatedAppAdminMigrationRouteImport } from './routes/_authenticated/app/admin/migration'
import { Route as AuthenticatedAppAccountsAccountIdRouteImport } from './routes/_authenticated/app/accounts/$accountId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppCategoriesRouteRoute =
  AuthenticatedAppCategoriesRouteRouteImport.update({
    id: '/app/categories',
    path: '/app/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminRouteRoute =
  AuthenticatedAppAdminRouteRouteImport.update({
    id: '/app/admin',
    path: '/app/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAccountsRouteRoute =
  AuthenticatedAppAccountsRouteRouteImport.update({
    id: '/app/accounts',
    path: '/app/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCategoriesIndexRoute =
  AuthenticatedAppCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCategoriesRouteRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRouteRoute,
  } as any)
const AuthenticatedAppAccountsIndexRoute =
  AuthenticatedAppAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAccountsRouteRoute,
  } as any)
const AuthenticatedAppAdminMigrationRoute =
  AuthenticatedAppAdminMigrationRouteImport.update({
    id: '/migration',
    path: '/migration',
    getParentRoute: () => AuthenticatedAppAdminRouteRoute,
  } as any)
const AuthenticatedAppAccountsAccountIdRoute =
  AuthenticatedAppAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAppAccountsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/accounts': typeof AuthenticatedAppAccountsRouteRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRouteRouteWithChildren
  '/app/categories': typeof AuthenticatedAppCategoriesRouteRouteWithChildren
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAccountsAccountIdRoute
  '/app/admin/migration': typeof AuthenticatedAppAdminMigrationRoute
  '/app/accounts/': typeof AuthenticatedAppAccountsIndexRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/categories/': typeof AuthenticatedAppCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAccountsAccountIdRoute
  '/app/admin/migration': typeof AuthenticatedAppAdminMigrationRoute
  '/app/accounts': typeof AuthenticatedAppAccountsIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/categories': typeof AuthenticatedAppCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/app/accounts': typeof AuthenticatedAppAccountsRouteRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteRouteWithChildren
  '/_authenticated/app/categories': typeof AuthenticatedAppCategoriesRouteRouteWithChildren
  '/_authenticated/app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/app/accounts/$accountId': typeof AuthenticatedAppAccountsAccountIdRoute
  '/_authenticated/app/admin/migration': typeof AuthenticatedAppAdminMigrationRoute
  '/_authenticated/app/accounts/': typeof AuthenticatedAppAccountsIndexRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/categories/': typeof AuthenticatedAppCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app/accounts'
    | '/app/admin'
    | '/app/categories'
    | '/app/home'
    | '/app/accounts/$accountId'
    | '/app/admin/migration'
    | '/app/accounts/'
    | '/app/admin/'
    | '/app/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/home'
    | '/app/accounts/$accountId'
    | '/app/admin/migration'
    | '/app/accounts'
    | '/app/admin'
    | '/app/categories'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/app/accounts'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/categories'
    | '/_authenticated/app/home'
    | '/_authenticated/app/accounts/$accountId'
    | '/_authenticated/app/admin/migration'
    | '/_authenticated/app/accounts/'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/home': {
      id: '/_authenticated/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/categories': {
      id: '/_authenticated/app/categories'
      path: '/app/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AuthenticatedAppCategoriesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/accounts': {
      id: '/_authenticated/app/accounts'
      path: '/app/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AuthenticatedAppAccountsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/categories/': {
      id: '/_authenticated/app/categories/'
      path: '/'
      fullPath: '/app/categories/'
      preLoaderRoute: typeof AuthenticatedAppCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAppCategoriesRouteRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRouteRoute
    }
    '/_authenticated/app/accounts/': {
      id: '/_authenticated/app/accounts/'
      path: '/'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AuthenticatedAppAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAccountsRouteRoute
    }
    '/_authenticated/app/admin/migration': {
      id: '/_authenticated/app/admin/migration'
      path: '/migration'
      fullPath: '/app/admin/migration'
      preLoaderRoute: typeof AuthenticatedAppAdminMigrationRouteImport
      parentRoute: typeof AuthenticatedAppAdminRouteRoute
    }
    '/_authenticated/app/accounts/$accountId': {
      id: '/_authenticated/app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAppAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAppAccountsRouteRoute
    }
  }
}

interface AuthenticatedAppAccountsRouteRouteChildren {
  AuthenticatedAppAccountsAccountIdRoute: typeof AuthenticatedAppAccountsAccountIdRoute
  AuthenticatedAppAccountsIndexRoute: typeof AuthenticatedAppAccountsIndexRoute
}

const AuthenticatedAppAccountsRouteRouteChildren: AuthenticatedAppAccountsRouteRouteChildren =
  {
    AuthenticatedAppAccountsAccountIdRoute:
      AuthenticatedAppAccountsAccountIdRoute,
    AuthenticatedAppAccountsIndexRoute: AuthenticatedAppAccountsIndexRoute,
  }

const AuthenticatedAppAccountsRouteRouteWithChildren =
  AuthenticatedAppAccountsRouteRoute._addFileChildren(
    AuthenticatedAppAccountsRouteRouteChildren,
  )

interface AuthenticatedAppAdminRouteRouteChildren {
  AuthenticatedAppAdminMigrationRoute: typeof AuthenticatedAppAdminMigrationRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedAppAdminRouteRouteChildren: AuthenticatedAppAdminRouteRouteChildren =
  {
    AuthenticatedAppAdminMigrationRoute: AuthenticatedAppAdminMigrationRoute,
    AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  }

const AuthenticatedAppAdminRouteRouteWithChildren =
  AuthenticatedAppAdminRouteRoute._addFileChildren(
    AuthenticatedAppAdminRouteRouteChildren,
  )

interface AuthenticatedAppCategoriesRouteRouteChildren {
  AuthenticatedAppCategoriesIndexRoute: typeof AuthenticatedAppCategoriesIndexRoute
}

const AuthenticatedAppCategoriesRouteRouteChildren: AuthenticatedAppCategoriesRouteRouteChildren =
  {
    AuthenticatedAppCategoriesIndexRoute: AuthenticatedAppCategoriesIndexRoute,
  }

const AuthenticatedAppCategoriesRouteRouteWithChildren =
  AuthenticatedAppCategoriesRouteRoute._addFileChildren(
    AuthenticatedAppCategoriesRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppAccountsRouteRoute: typeof AuthenticatedAppAccountsRouteRouteWithChildren
  AuthenticatedAppAdminRouteRoute: typeof AuthenticatedAppAdminRouteRouteWithChildren
  AuthenticatedAppCategoriesRouteRoute: typeof AuthenticatedAppCategoriesRouteRouteWithChildren
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAccountsRouteRoute:
    AuthenticatedAppAccountsRouteRouteWithChildren,
  AuthenticatedAppAdminRouteRoute: AuthenticatedAppAdminRouteRouteWithChildren,
  AuthenticatedAppCategoriesRouteRoute:
    AuthenticatedAppCategoriesRouteRouteWithChildren,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
