/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppHomeRouteImport } from './routes/_authenticated/app/home'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/app/activity'
import { Route as AuthenticatedAppAccountsRouteRouteImport } from './routes/_authenticated/app/accounts/route'
import { Route as AuthenticatedAppAccountsIndexRouteImport } from './routes/_authenticated/app/accounts/index'
import { Route as AuthenticatedAppAccountsAccountIdRouteImport } from './routes/_authenticated/app/accounts/$accountId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppHomeRoute = AuthenticatedAppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/app/activity',
    path: '/app/activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAccountsRouteRoute =
  AuthenticatedAppAccountsRouteRouteImport.update({
    id: '/app/accounts',
    path: '/app/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAccountsIndexRoute =
  AuthenticatedAppAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAccountsRouteRoute,
  } as any)
const AuthenticatedAppAccountsAccountIdRoute =
  AuthenticatedAppAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => AuthenticatedAppAccountsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/accounts': typeof AuthenticatedAppAccountsRouteRouteWithChildren
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAccountsAccountIdRoute
  '/app/accounts/': typeof AuthenticatedAppAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/home': typeof AuthenticatedAppHomeRoute
  '/app/accounts/$accountId': typeof AuthenticatedAppAccountsAccountIdRoute
  '/app/accounts': typeof AuthenticatedAppAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/app/accounts': typeof AuthenticatedAppAccountsRouteRouteWithChildren
  '/_authenticated/app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/app/home': typeof AuthenticatedAppHomeRoute
  '/_authenticated/app/accounts/$accountId': typeof AuthenticatedAppAccountsAccountIdRoute
  '/_authenticated/app/accounts/': typeof AuthenticatedAppAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app/accounts'
    | '/app/activity'
    | '/app/home'
    | '/app/accounts/$accountId'
    | '/app/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/activity'
    | '/app/home'
    | '/app/accounts/$accountId'
    | '/app/accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/app/accounts'
    | '/_authenticated/app/activity'
    | '/_authenticated/app/home'
    | '/_authenticated/app/accounts/$accountId'
    | '/_authenticated/app/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/home': {
      id: '/_authenticated/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AuthenticatedAppHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/activity': {
      id: '/_authenticated/app/activity'
      path: '/app/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/accounts': {
      id: '/_authenticated/app/accounts'
      path: '/app/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AuthenticatedAppAccountsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/accounts/': {
      id: '/_authenticated/app/accounts/'
      path: '/'
      fullPath: '/app/accounts/'
      preLoaderRoute: typeof AuthenticatedAppAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAccountsRouteRoute
    }
    '/_authenticated/app/accounts/$accountId': {
      id: '/_authenticated/app/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/app/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAppAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAppAccountsRouteRoute
    }
  }
}

interface AuthenticatedAppAccountsRouteRouteChildren {
  AuthenticatedAppAccountsAccountIdRoute: typeof AuthenticatedAppAccountsAccountIdRoute
  AuthenticatedAppAccountsIndexRoute: typeof AuthenticatedAppAccountsIndexRoute
}

const AuthenticatedAppAccountsRouteRouteChildren: AuthenticatedAppAccountsRouteRouteChildren =
  {
    AuthenticatedAppAccountsAccountIdRoute:
      AuthenticatedAppAccountsAccountIdRoute,
    AuthenticatedAppAccountsIndexRoute: AuthenticatedAppAccountsIndexRoute,
  }

const AuthenticatedAppAccountsRouteRouteWithChildren =
  AuthenticatedAppAccountsRouteRoute._addFileChildren(
    AuthenticatedAppAccountsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppAccountsRouteRoute: typeof AuthenticatedAppAccountsRouteRouteWithChildren
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppHomeRoute: typeof AuthenticatedAppHomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAccountsRouteRoute:
    AuthenticatedAppAccountsRouteRouteWithChildren,
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppHomeRoute: AuthenticatedAppHomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
